title: Hantao Huang | Personal Homepage
page-top-title: Hantao Huang
top-section-bg-text: AI Hardware-Software Co-Design | LLM Optimization | Edge Intelligence
home-subtitle: '<i class="bi bi-person-vcard-fill"></i>&nbsp;ABOUT ME'
copyright-text: "&copy; Hantao Huang 2026. All Rights Reserved."
